package com.custom.query;

import com.custom.query.model.User;
import com.custom.query.repository.UserRepository;
import com.custom.query.service.UserService;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.ConfigurableApplicationContext;

import java.util.List;
import java.util.Random;

@SpringBootApplication
public class QueryApplication {

	public static void main(String[] args) {
		ConfigurableApplicationContext context =SpringApplication.run(QueryApplication.class, args);
		UserRepository repository = context.getBean(UserRepository.class);
		Iterable<User> users = repository.findAll();
		users.forEach(user -> {
			System.out.println(user.getName());
		});
		System.out.println("########################################");
		List<User> users1 = repository.getAllUserHql();
		users1.forEach(user -> {
			System.out.println("values   :::  "+user);
		});

		System.out.println("########################################");
		List<User> users2 = repository.getAllUserSql();
		users2.forEach(user -> {
			System.out.println("values :::  "+user);
		});

		System.out.println("########################################");
		List<User> users3 = repository.getAllUserByCountry("India");
		users3.forEach(user -> {
			System.out.println("values By Country :::  "+user);
		});
		System.out.println("######################################## values By Country using sql query ");
		List<User> users4 = repository.getAllUserByCountryUsingSql("India");
		users4.forEach(user -> {
			System.out.println("sql query:::  "+user);
		});
		UserService userService = new UserService(repository);

		System.out.println("######################################## inserting values in database using native query ");
//		userService.insertUser(112, "Cathrine", "FEMALE", "CANADA", 28);
//
//		userService.insertUser(114, "Alice", "FEMALE", "USA", 28);
//		userService.insertUser(115, "Bob", "MALE", "Canada", 35);
//		userService.insertUser(116, "Eva", "FEMALE", "UK", 29);
//		userService.insertUser(117, "David", "MALE", "Australia", 42);
//		userService.insertUser(118, "Lily", "FEMALE", "France", 31);
//		userService.insertUser(119, "John", "MALE", "Germany", 37);
//		userService.insertUser(120, "Sophia", "FEMALE", "Spain", 26);
//		userService.insertUser(121, "Michael", "MALE", "Italy", 39);
//		userService.insertUser(122, "Olivia", "FEMALE", "Japan", 33);
//		userService.insertUser(123, "Daniel", "MALE", "South Korea", 30);
//		userService.insertUser(124, "Emily", "FEMALE", "Brazil", 27);
//		userService.insertUser(125, "Matthew", "MALE", "Mexico", 36);
//		userService.insertUser(126, "Ava", "FEMALE", "India", 32);
//		userService.insertUser(127, "William", "MALE", "China", 34);
//		userService.insertUser(128, "Sofia", "FEMALE", "Russia", 29);
//		userService.insertUser(129, "Joseph", "MALE", "South Africa", 40);
//		userService.insertUser(130, "Mia", "FEMALE", "New Zealand", 28);
//		userService.insertUser(131, "Andrew", "MALE", "Ireland", 38);
//		userService.insertUser(132, "Grace", "FEMALE", "Sweden", 25);
//		userService.insertUser(133, "Christopher", "MALE", "Norway", 41);
//		userService.insertUser(134, "Sophie", "FEMALE", "Canada", 29);
//		userService.insertUser(135, "Jacob", "MALE", "USA", 34);
//		userService.insertUser(136, "Charlotte", "FEMALE", "UK", 31);
//		userService.insertUser(137, "Ethan", "MALE", "Australia", 37);
//		userService.insertUser(138, "Oliver", "MALE", "France", 28);
//		userService.insertUser(139, "Mia", "FEMALE", "Germany", 26);
//		userService.insertUser(140, "Lucas", "MALE", "Spain", 33);
//		userService.insertUser(141, "Amelia", "FEMALE", "Italy", 40);
//		userService.insertUser(142, "Noah", "MALE", "Japan", 36);
//		userService.insertUser(143, "Ella", "FEMALE", "South Korea", 27);
//		userService.insertUser(144, "Alexander", "MALE", "Brazil", 38);
//		userService.insertUser(145, "Emma", "FEMALE", "Mexico", 32);
//		userService.insertUser(146, "Liam", "MALE", "India", 30);
//		userService.insertUser(147, "Aria", "FEMALE", "China", 29);
//		userService.insertUser(148, "Benjamin", "MALE", "Russia", 42);
//		userService.insertUser(149, "Zoe", "FEMALE", "South Africa", 31);
//		userService.insertUser(150, "Daniel", "MALE", "New Zealand", 35);
//		userService.insertUser(151, "Avery", "FEMALE", "Ireland", 34);
//		userService.insertUser(152, "Jackson", "MALE", "Sweden", 29);
//		userService.insertUser(153, "Sophia", "FEMALE", "Norway", 27);
//		userService.insertUser(154, "Liam", "MALE", "Canada", 33);
//		userService.insertUser(155, "Ava", "FEMALE", "USA", 30);
//		userService.insertUser(156, "Elijah", "MALE", "UK", 35);
//		userService.insertUser(157, "Grace", "FEMALE", "Australia", 29);
//		userService.insertUser(158, "Lucas", "MALE", "France", 37);
//		userService.insertUser(159, "Avery", "FEMALE", "Germany", 32);
//		userService.insertUser(160, "Olivia", "FEMALE", "Spain", 28);
//		userService.insertUser(161, "Logan", "MALE", "Italy", 39);
//		userService.insertUser(162, "Amelia", "FEMALE", "Japan", 36);
//		userService.insertUser(163, "Noah", "MALE", "South Korea", 26);
//		userService.insertUser(164, "Lily", "FEMALE", "Brazil", 41);
//		userService.insertUser(165, "Mason", "MALE", "Mexico", 27);
//		userService.insertUser(166, "Harper", "FEMALE", "India", 30);
//		userService.insertUser(167, "Benjamin", "MALE", "China", 35);
//		userService.insertUser(168, "Ella", "FEMALE", "Russia", 31);
//		userService.insertUser(169, "Carter", "MALE", "South Africa", 33);
//		userService.insertUser(170, "Zoe", "FEMALE", "New Zealand", 34);
//		userService.insertUser(171, "Michael", "MALE", "Ireland", 37);
//		userService.insertUser(172, "Sophia", "FEMALE", "Sweden", 29);
//		userService.insertUser(173, "Ethan", "MALE", "Norway", 30);
//		userService.insertUser(174, "Aiden", "MALE", "Canada", 32);
//		userService.insertUser(175, "Aria", "FEMALE", "USA", 29);
//		userService.insertUser(176, "William", "MALE", "UK", 37);
//		userService.insertUser(177, "Charlotte", "FEMALE", "Australia", 31);
//		userService.insertUser(178, "Oliver", "MALE", "France", 28);
//		userService.insertUser(179, "Ella", "FEMALE", "Germany", 33);
//		userService.insertUser(180, "Elijah", "MALE", "Spain", 40);
//		userService.insertUser(181, "Grace", "FEMALE", "Italy", 35);
//		userService.insertUser(182, "Mason", "MALE", "Japan", 34);
//		userService.insertUser(183, "Sophia", "FEMALE", "South Korea", 30);
//		userService.insertUser(184, "James", "MALE", "Brazil", 39);
//		userService.insertUser(185, "Lily", "FEMALE", "Mexico", 27);
//		userService.insertUser(186, "Benjamin", "MALE", "India", 42);
//		userService.insertUser(187, "Emma", "FEMALE", "China", 29);
//		userService.insertUser(188, "Lucas", "MALE", "Russia", 38);
//		userService.insertUser(189, "Harper", "FEMALE", "South Africa", 36);
//		userService.insertUser(190, "Henry", "MALE", "New Zealand", 33);
//		userService.insertUser(191, "Olivia", "FEMALE", "Ireland", 26);
//		userService.insertUser(192, "Liam", "MALE", "Sweden", 31);
//		userService.insertUser(193, "Avery", "FEMALE", "Norway", 32);
//		userService.insertUser(194, "Jackson", "MALE", "Canada", 34);
//		userService.insertUser(195, "Mia", "FEMALE", "USA", 30);
//		userService.insertUser(196, "Ethan", "MALE", "UK", 35);
//		userService.insertUser(197, "Isabella", "FEMALE", "Australia", 29);
//		userService.insertUser(198, "Lucy", "FEMALE", "France", 28);
//		userService.insertUser(199, "Alexander", "MALE", "Germany", 37);
//		userService.insertUser(200, "Aiden", "MALE", "Spain", 31);
//		userService.insertUser(201, "Abigail", "FEMALE", "Italy", 38);
//		userService.insertUser(202, "Daniel", "MALE", "Japan", 40);
//		userService.insertUser(203, "Nora", "FEMALE", "South Korea", 34);
//		userService.insertUser(204, "Jacob", "MALE", "Brazil", 36);
//		userService.insertUser(205, "Emily", "FEMALE", "Mexico", 33);
//		userService.insertUser(206, "Aria", "FEMALE", "India", 30);
//		userService.insertUser(207, "William", "MALE", "China", 41);
//		userService.insertUser(208, "Grace", "FEMALE", "Russia", 32);
//		userService.insertUser(209, "Noah", "MALE", "South Africa", 35);
//		userService.insertUser(210, "Chloe", "FEMALE", "New Zealand", 28);
//		userService.insertUser(211, "Michael", "MALE", "Ireland", 42);
//		userService.insertUser(212, "Sophie", "FEMALE", "Sweden", 29);
//		userService.insertUser(213, "Ella", "FEMALE", "Norway", 33);
//		userService.insertUser(214, "Lucas", "MALE", "Canada", 37);
//		userService.insertUser(215, "Harper", "FEMALE", "USA", 31);
//		userService.insertUser(216, "Ethan", "MALE", "UK", 30);
//		userService.insertUser(217, "Avery", "FEMALE", "Australia", 36);
//		userService.insertUser(218, "Logan", "MALE", "France", 29);
//		userService.insertUser(219, "Olivia", "FEMALE", "Germany", 38);
//		userService.insertUser(220, "Emma", "FEMALE", "Spain", 34);
//		userService.insertUser(221, "Benjamin", "MALE", "Italy", 27);
//		userService.insertUser(222, "Sophia", "FEMALE", "Japan", 32);
//		userService.insertUser(223, "Noah", "MALE", "South Korea", 35);
//		userService.insertUser(224, "Oliver", "MALE", "Canada", 28);
//		userService.insertUser(225, "Sophia", "FEMALE", "USA", 32);
//		userService.insertUser(226, "Ethan", "MALE", "UK", 36);
//		userService.insertUser(227, "Mia", "FEMALE", "Australia", 29);
//		userService.insertUser(228, "Liam", "MALE", "France", 37);
//		userService.insertUser(229, "Isabella", "FEMALE", "Germany", 31);
//		userService.insertUser(230, "Lucas", "MALE", "Spain", 33);
//		userService.insertUser(231, "Ava", "FEMALE", "Italy", 40);
//		userService.insertUser(232, "Noah", "MALE", "Japan", 34);
//		userService.insertUser(233, "Emily", "FEMALE", "South Korea", 29);
//		userService.insertUser(234, "James", "MALE", "Brazil", 28);
//		userService.insertUser(235, "Lily", "FEMALE", "Mexico", 35);
//		userService.insertUser(236, "Jacob", "MALE", "India", 32);
//		userService.insertUser(237, "Olivia", "FEMALE", "China", 26);
//		userService.insertUser(238, "Charlotte", "FEMALE", "Russia", 31);
//		userService.insertUser(239, "Elijah", "MALE", "South Africa", 38);
//		userService.insertUser(240, "Avery", "FEMALE", "New Zealand", 27);
//		userService.insertUser(241, "Daniel", "MALE", "Ireland", 42);
//		userService.insertUser(242, "Sophie", "FEMALE", "Sweden", 30);
//		userService.insertUser(243, "Aiden", "MALE", "Norway", 33);
//		userService.insertUser(244, "Harper", "FEMALE", "Canada", 36);
//		userService.insertUser(245, "William", "MALE", "USA", 31);
//		userService.insertUser(246, "Ella", "FEMALE", "UK", 28);
//		userService.insertUser(247, "Ethan", "MALE", "Australia", 37);
//		userService.insertUser(248, "Mia", "FEMALE", "France", 34);
//		userService.insertUser(249, "Lucas", "MALE", "Germany", 29);
//		userService.insertUser(250, "Sophia", "FEMALE", "Spain", 40);
//		userService.insertUser(251, "Oliver", "MALE", "Italy", 33);
//		userService.insertUser(252, "Ava", "FEMALE", "Japan", 35);
//		userService.insertUser(253, "Noah", "MALE", "South Korea", 30);
//		userService.insertUser(254, "Emily", "FEMALE", "Brazil", 32);
//		userService.insertUser(255, "James", "MALE", "Mexico", 39);
//		userService.insertUser(256, "Lily", "FEMALE", "India", 37);
//		userService.insertUser(257, "Jacob", "MALE", "China", 31);
//		userService.insertUser(258, "Olivia", "FEMALE", "Russia", 26);
//		userService.insertUser(259, "Charlotte", "FEMALE", "South Africa", 38);
//		userService.insertUser(260, "Elijah", "MALE", "New Zealand", 27);
//		userService.insertUser(261, "Avery", "FEMALE", "Ireland", 35);
//		userService.insertUser(262, "Sophie", "FEMALE", "Sweden", 34);
//		userService.insertUser(263, "Aiden", "MALE", "Norway", 32);
//		userService.insertUser(264, "Harper", "FEMALE", "Canada", 29);
//		userService.insertUser(265, "William", "MALE", "USA", 30);
//		userService.insertUser(266, "Ella", "FEMALE", "UK", 36);
//		userService.insertUser(267, "Ethan", "MALE", "Australia", 31);
//		userService.insertUser(268, "Mia", "FEMALE", "France", 28);
//		userService.insertUser(269, "Lucas", "MALE", "Germany", 33);
//		userService.insertUser(270, "Sophia", "FEMALE", "Spain", 35);
//		userService.insertUser(271, "Ava", "FEMALE", "Canada", 30);
//		userService.insertUser(272, "Liam", "MALE", "USA", 26);
//		userService.insertUser(273, "Olivia", "FEMALE", "UK", 41);
//		userService.insertUser(274, "Noah", "MALE", "Australia", 38);
//		userService.insertUser(275, "Emma", "FEMALE", "France", 34);
//		userService.insertUser(276, "Lucas", "MALE", "Germany", 47);
//		userService.insertUser(277, "Sophia", "FEMALE", "Spain", 29);
//		userService.insertUser(278, "Elijah", "MALE", "Italy", 50);
//		userService.insertUser(279, "Mia", "FEMALE", "Japan", 23);
//		userService.insertUser(280, "Aiden", "MALE", "South Korea", 27);
//		userService.insertUser(281, "Oliver", "MALE", "Brazil", 38);
//		userService.insertUser(282, "Charlotte", "FEMALE", "Mexico", 52);
//		userService.insertUser(283, "William", "MALE", "India", 45);
//		userService.insertUser(284, "Aria", "FEMALE", "China", 18);
//		userService.insertUser(285, "Daniel", "MALE", "Russia", 32);
//		userService.insertUser(286, "Grace", "FEMALE", "South Africa", 44);
//		userService.insertUser(287, "Eva", "FEMALE", "New Zealand", 21);
//		userService.insertUser(288, "Logan", "MALE", "Ireland", 39);
//		userService.insertUser(289, "Harper", "FEMALE", "Sweden", 49);
//		userService.insertUser(290, "Mason", "MALE", "Norway", 42);
//		userService.insertUser(291, "Lily", "FEMALE", "Canada", 25);
//		userService.insertUser(292, "Carter", "MALE", "USA", 36);
//		userService.insertUser(293, "Sophie", "FEMALE", "UK", 46);
//		userService.insertUser(294, "Ethan", "MALE", "Australia", 31);
//		userService.insertUser(295, "Avery", "FEMALE", "France", 20);
//		userService.insertUser(296, "Benjamin", "MALE", "Germany", 35);
//		userService.insertUser(297, "Aria", "FEMALE", "Spain", 10);
//		userService.insertUser(298, "Ella", "FEMALE", "Italy", 54);
//		userService.insertUser(299, "Liam", "MALE", "Japan", 37);
//		userService.insertUser(300, "Zoe", "FEMALE", "South Korea", 51);
//		userService.insertUser(301, "Lucas", "MALE", "Brazil", 33);
//		userService.insertUser(302, "Sofia", "FEMALE", "Mexico", 22);
//		userService.insertUser(303, "William", "MALE", "India", 26);
//		userService.insertUser(304, "Sophia", "FEMALE", "China", 40);
//		userService.insertUser(305, "Ella", "FEMALE", "Russia", 56);
//		userService.insertUser(306, "Michael", "MALE", "South Africa", 28);
//		userService.insertUser(307, "Isabella", "FEMALE", "New Zealand", 43);
//		userService.insertUser(308, "Liam", "MALE", "Ireland", 47);
//		userService.insertUser(309, "Ava", "FEMALE", "Sweden", 30);
//		userService.insertUser(310, "Lucy", "FEMALE", "Norway", 44);
//		userService.insertUser(311, "Jackson", "MALE", "Canada", 48);
//		userService.insertUser(312, "Ethan", "MALE", "USA", 52);
//		userService.insertUser(313, "Emma", "FEMALE", "UK", 26);
//		userService.insertUser(314, "Olivia", "FEMALE", "Australia", 38);
//		userService.insertUser(315, "Elijah", "MALE", "France", 41);
//		userService.insertUser(316, "Avery", "FEMALE", "Germany", 20);
//		userService.insertUser(317, "Noah", "MALE", "Spain", 32);
//		userService.insertUser(318, "Lily", "FEMALE", "Italy", 37);
//		userService.insertUser(319, "Aria", "FEMALE", "Japan", 49);
//		userService.insertUser(320, "James", "MALE", "South Korea", 30);
//

	}

}
